const projectCount = require("../../../data/projects.json").length;
const { test, expect } = require("@playwright/test");
async function openMenu(page) {
  const menu = page.locator("#site-navigation");
  if (!await menu.evaluate(node => node.open)) await menu.locator("summary").click();
  return menu;
}
test("ordinary page navigation shares URLs and survives back, forward and reload", async ({ page, request }, testInfo) => {
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  const catalog = await (await request.get("/blog/articles.json")).json();
  await page.goto("/");
  await expect(page.locator("frameset,frame")).toHaveCount(0);
  await expect(page.locator(".home-hero h1")).toContainText("Xenoah");
  const menu = await openMenu(page);
  await menu.locator('.menu-main a[href="/portfolio.htm"]').click();
  await expect(page).toHaveURL(/\/portfolio.htm$/);
  await page.reload(); await expect(page.locator(".hero h1")).toBeVisible();
  await (await openMenu(page)).locator('.menu-main a[href="/blog/"]').click();
  await page.locator(".post-card a").first().click();
  const sharedUrl = page.url();
  await expect(page.locator(".article-head h1")).toHaveText(catalog[0].title);
  await page.reload(); await expect(page).toHaveURL(sharedUrl);
  await page.locator('.post-nav a[href="/blog/"]').click();
  await page.goBack(); await expect(page).toHaveURL(sharedUrl);
  await expect(page.locator(".article-head h1")).toHaveText(catalog[0].title);
  await page.goForward(); await expect(page).toHaveURL(/\/blog\/$/);
  expect(errors).toEqual([]);
  await page.goto("/");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await testInfo.attach("Homepage", { body: await page.screenshot({ fullPage: true }), contentType: "image/png" });
});
test("catalog filters preserve URLs and expose both Pages and GitHub", async ({ page }) => {
  await page.goto("/projects.htm");
  const content = page.locator("#main-content");
  const form = content.locator("[data-project-filters]");
  await form.locator('[name="q"]').fill("ＳＶＧ");
  await expect(content.locator("[data-project]:visible")).toHaveCount(1);
  await expect(content.locator('[data-project]:visible a[href="/tools/svg-converter/svg-converter.htm"]')).toHaveCount(2);
  await expect(content.locator('[data-project]:visible a[href="https://github.com/Xenoah/Xenoah.github.io/tree/main/tools/svg-converter"]')).toBeVisible();
  await page.reload(); await expect(form.locator('[name="q"]')).toHaveValue("ＳＶＧ");
  await form.locator('[name="category"]').selectOption("music");
  await expect(content.locator("[data-project]:visible")).toHaveCount(0);
  await expect(form.locator("[role=status]")).toContainText("該当する作品がありません");
  await form.getByRole("button", { name: "条件をクリア" }).click();
  await expect(content.locator("[data-project]:visible")).toHaveCount(projectCount);
  await form.locator('[name="q"]').fill("VoiceMeld");
  await expect(content.locator('[data-project]:visible a[href="https://github.com/Xenoah/voicemeld"]')).toHaveCount(2);
  await expect(content.locator('[data-project]:visible a[href="/voicemeld/"]')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
test("mobile menu supports keyboard dismissal and desktop resizing", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/");
  const menu = page.locator("#site-navigation");
  await expect(menu).toHaveJSProperty("open", false);
  await menu.locator("summary").focus(); await page.keyboard.press("Enter");
  await expect(menu).toHaveJSProperty("open", true);
  await menu.locator('[name="q"]').fill("SVG");
  await expect(menu.locator("[data-project]:visible")).toHaveCount(1);
  await page.keyboard.press("Escape"); await expect(menu).toHaveJSProperty("open", false);
  await expect(menu.locator("summary")).toBeFocused();
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(menu).toHaveJSProperty("open", true);
});
test("old top, menu-view and Japanese blog links still resolve without external redirects", async ({ page, request }) => {
  const current = "/blog/2026/09/05/madomagi/";
  const catalog = await (await request.get("/blog/articles.json")).json();
  const article = catalog.find(entry => entry.url === current);
  await page.goto("/top.htm"); await expect(page).toHaveURL(/\/$/);
  await page.goto("/blog/2026/09/05/ネタバレ注意-まどマギ-ワルプルギスの廻天考察/?view=menu#section-1");
  await expect(page).toHaveURL(new RegExp(current + "#section-1$"));
  await expect(page.locator(".article-head h1")).toHaveText(article.title);
  await page.goto("/blog/2026/09/05/madoka-walpurgisnacht-rising-review/");
  await expect(page).toHaveURL(new RegExp(current + "$"));
  await page.goto("/?blog=" + encodeURIComponent(current + "#section-1"));
  await expect(page).toHaveURL(new RegExp(current + "#section-1$"));
  await page.goto("/?blog=" + encodeURIComponent("https://example.com/blog/2026/09/05/other/"));
  await expect(page.locator(".home-hero")).toBeVisible();
  expect(new URL(page.url()).pathname).toBe("/");
});
test("legacy editor entry retains local drafts with ordinary navigation", async ({ page }) => {
  await page.goto("/blog/editor.html?view=menu");
  await expect(page).toHaveURL(/\/blog\/editor.html$/);
  await expect(page.locator("#editorApp")).toHaveJSProperty("inert", false);
  await page.locator("#title").fill("日本語の記事タイトル");
  await page.locator("#body").fill("記事の本文です。");
  await expect(page.locator("#slug")).toHaveValue(/^article-[a-z0-9]+$/);
  await page.locator("#saveDraftBtn").click();
  await expect(page.locator("#draftSaved")).toContainText("保存済み");
  await page.reload(); await expect(page.locator("#title")).toHaveValue("日本語の記事タイトル");
  await expect(page.locator("#body")).toHaveText("記事の本文です。");
});
test("navigation and all project links work without JavaScript", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false });
  const page = await context.newPage();
  await page.goto("http://127.0.0.1:4173/projects.htm");
  await expect(page.locator("#main-content [data-project]")).toHaveCount(projectCount);
  await expect(page.locator("#main-content [data-project-filters]")).toBeHidden();
  await page.locator('.menu-main a[href="/portfolio.htm"]').click();
  await expect(page.locator(".hero h1")).toBeVisible();
  await context.close();
});
